### ISSUE TITLE
Make An API for the functionality

### ISSUE THREAD

**Issue by adrian-chang** [nobitagit/material-floating-button#1]
Hey this is a pretty cool library in general. Can do the snazzy inbox + button effects with only CSS but I think it would be a good idea to at least provide a simple JS API, for example, to force the menu open and stuff without people writing custom code to pop open everything or to link a button with a specific action.

**Comment by nobitagit** [comment]
Yes, i do agree completely that a js api is needed, especially because CSS can't provide touch support, which is essential. 
This is actually in the works at the moment and should land in the master branch pretty soon.

**Comment by nobitagit** [comment]
Added touch support and the ability to open/close the menu programmatically with the last update.
