### ISSUE TITLE
Vertical Align Ionicons

### ISSUE THREAD

**Issue by tomwhita** [nobitagit/material-floating-button#17]
I'm trying to implement this button on my wordpress site and I've run into an issue where the button icons are not properly aligned vertically.  I can't seem to figure out why.  Any chance you could help?
![screenshot 2015-11-25 19 35 31](https://cloud.githubusercontent.com/assets/6446995/11412490/bce870e6-93ab-11e5-968e-d61d2bc08a48.png)

**Comment by nobitagit** [comment]
Any chance you can share a public URL?

**Comment by tomwhita** [comment]
You can access the site here:

htttp://trudel.stageing.harnessup.com

Username: tomwhita
Password: password

Thanks

**Comment by tomwhita** [comment]
Sorry URL is /dashboard

**Comment by nobitagit** [comment]
Hi,
please don't share your login details, I just need a publicly accessible page where I can actually see the button in place and see the issue

**Comment by tomwhita** [comment]
The URL is for our staging server and I've set a temp password so that you
can access it. No sensitive info is available there.

**Comment by nobitagit** [comment]
Ok, but is there a page where I can actually see the menu rendered?

**Comment by tomwhita** [comment]
http://trudel.stageing.harnessup.com/dashboard

**Comment by nobitagit** [comment]
The markup of the button in that page is different from the one that you see in the examples of this component. It contains `<br>` and empty `<p>` tags that change the layout and actually make the html invalid.

This code for example:

``` html
<ul class="mfb-component--tr mfb-zoomin" data-mfb-toggle="hover" style="display: block;">
<li class="mfb-component__wrap">
    <!-- this br tag is not needed-><br>
    <a data-mfb-label="Add A New Project" class="mfb-component__button--main"><br>
      <!-- this br tag is not needed-><br>
      <i class="mfb-component__main-icon--resting ion-plus-round"></i><br>
      <!-- this br tag is not needed-><br>
      <i class="mfb-component__main-icon--active ion-close-round"></i><br>
    </a><p></p>
<ul class="mfb-component__list">
      <!-- this p tag is not needed-><p></p>
<li>
```

Please make sure that the HTML reflects the one in the docs, as explained [here](https://github.com/nobitagit/material-floating-button#html)

**Comment by tomwhita** [comment]
Wow.  Am I stupid.  Thanks for looking into this.  I really appreciate it.
I was so focused on the CSS that I didn't look closer at the HTML.

TW
