### ISSUE TITLE
ASK - how to enter a code on wordpress?

### ISSUE THREAD

**Issue by eukaristia** [nobitagit/material-floating-button#19]
how to enter a code on wordpress

**Comment by nobitagit** [comment]
Hi, 

this is a very broad question....
Anyway it's not different for inserting any kind of other html to a Wp site.

**Comment by eukaristia** [comment]
Im newbie hehe
I load mfb.css but not work

**Comment by eukaristia** [comment]
can u help me how to put css in header? to available button clickable not hover?

**Comment by nobitagit** [comment]
This is a Wp related question, and I haven't been using it in ages, you should look for help in a wp forum.
