### ISSUE TITLE
Number of items

### ISSUE THREAD

**Issue by dpdragnev** [nobitagit/material-floating-button#21]
Hello,

Firstly, awesome job on the library.  Very useful. 

I have a question regarding the number of buttons allowed.  I have a list of 13 buttons that I tried using, but only the first 4 are showing.  I am not getting any errors, the simply do not appear.  Is there a limit for the number of buttons allowed?

The documentation did not specify any limits and I assumed that there are none, but since only the first 4 are showing I thought I ask.

Thank you.

**Comment by nobitagit** [comment]
Hi there, 

please refer to #3 to see how this works, or check the documentation [here](https://github.com/nobitagit/material-floating-button#basic)
