### ISSUE TITLE
The page scrollToTop when clicking the button

### ISSUE THREAD

**Issue by jeanrinvil** [nobitagit/material-floating-button#26]
I use the button in my website and in my app but when I click the button, the page scroll to Top
It's a bit annoying..

How can I disable this ?

**Comment by theWhiteWulfy** [comment]
I don't know. Same happens with me too.

**Comment by theWhiteWulfy** [comment]
this happens if you have older(<3) version of jquery on that page

**Comment by theWhiteWulfy** [comment]
its a click event that is attached to body and send us to top(ie start of body)

**Comment by reki-cool** [comment]
Same happens with me too.

**Comment by jeanrinvil** [comment]
Hi guys, 

I solve the problem with this code : 

```
$('.mfb-component__button--main').click(function(evt) {
	evt.preventDefault()
})
```

**Comment by reki-cool** [comment]
good！
