### ISSUE TITLE
add support for different colors for the child buttons

### ISSUE THREAD

**Issue by notsatyarth** [nobitagit/material-floating-button#5]
Provide a different colour for each child button,either on hover.

Ps: I have done the hover change on [my website](https://github.com/droidekas/droidekas.github.io/commit/a95b3b2022e537281541311455726eb3221e70cf).I am new to sass so obviously its horrible code.But as an idea is this possible?

**Comment by nobitagit** [comment]
Sorry for missing this one and being so late. Color support is possible and easy achievable by adding a class, or targeting `nth-child` for each button we want to color.
