### ISSUE TITLE
label/button spacing for smaller buttons

### ISSUE THREAD

**Issue by catmsred** [nobitagit/material-floating-button#6]
The site I'm working on has fairly tight spacing, so I'm using fairly small buttons and margins.  With the hard-coded label placement and button stack spacing, the labels look a little strange, can overlap content:

![ng-mfb_current](https://cloud.githubusercontent.com/assets/9269830/6626701/3c57a02a-c8cf-11e4-9ace-fd990bd3b80d.png)

After poking around the sass/css available, I ended up with a layout I'm generally pleased with.

![ng-mfb_patch](https://cloud.githubusercontent.com/assets/9269830/6626768/a329d7aa-c8cf-11e4-8139-1eb552609c8e.png)

I added a new block of customizable variables to the scss code:

```
/* SPACING ---------------------------*/

// space between buttons
$default_button_padding: 30px;
$default_button_margin: 5px;

// space between button and label
$button_default_pos: 40px;
```

I changed your defaults in `.mfb-component__list` (10px for both padding and margin) to fix the spacing between buttons, and used `$button_default_pos` instead of 70px in the section `#LABELS | Modifiers`.

I'm not sure if this is a level of customization you want to support, but I thought I'd post it in case you were interested, or someone else had the same type layout.  :-/

Cheers,
Cat

**Comment by nobitagit** [comment]
These values are hard-coded but definitely call for a variable on their own, as you correctly suggest.

I know that at the moment the layout for smaller buttons is far from perfect and it's an issue that needs solved sooner or later. Lately I've been quite busy in porting this project to Angular and React, but it's about time I tackle some issues that were left behind.

Thanks for chiming in, don't forget that you can also fork this repo and submit a pull request if you want, obviously. Cheers.

**Comment by catmsred** [comment]
Thanks for the quick response!  I'm glad you're working on Angular, since that's the framework I'm working in. :smile_cat: 

I'll do a proper pull request tomorrow once I've checked that my changes don't break any of the cases I'm not using.
