### ISSUE TITLE
SASS default var def

### ISSUE THREAD

**Issue by mwinandy** [nobitagit/material-floating-button#8]
Hello,

To help theming of component, it will be great to add !default at end of var def on scss file instead of override import.

See: https://robots.thoughtbot.com/sass-default .

Thanks !

**Comment by nobitagit** [comment]
Went through the article but I might be missing the real advantage of doing this. I don't understand what is the real difference in the output as in both cases it seems to me that the final css wouldn't be any different. Isn't it?

**Comment by mwinandy** [comment]
The difference is on var surcharging from a parent scss file, because when I use mfb as bower component, I import the SCSS file from `bower_components`, and I won't modify or duplicate source SCSS, because it breaks during bower install.

Example: To change the value of `$main-color` (`#E40A5D` as default), I must redefine the value in `_customize.scss` with your technique. But as bower components, it will be not clean against bower install/update.

If you add `!default` at the end of variable def, you can override `$main-color` value in parent scss without change source file, if you define a value for `$main-color` before `@import "./bower_components/mfb.scss"`. It's cleaner than actual.

@nobitagit to answer, there is no output differencies but there are in the dependencies's maintenability

**Comment by nobitagit** [comment]
Still not really getting it but it may be just because i've just never used that technique. Care/time to make a pull request for this?

**Comment by cmfcmf** [comment]
I'd really like this to happen :+1:

**Comment by nobitagit** [comment]
Merged the PR, will make a new npm release as soon as possible.

ps - (unrelated to this issue) @cmfcmf as you are among the contributors let me know if you'd like to have your name and/or email added to the contributors list of this repo or just edit the package.json and make a quick PR for this, as you like.

**Comment by cmfcmf** [comment]
@nobitagit Done, please see https://github.com/nobitagit/material-floating-button/pull/10.
